
output:
    'pipeline'

kasel-data:
    'kasel/data'

krakendb:
    'krakendb/kraken2_20210922/'

default:
    threads: 1
    memory: "4G"

alignment_pe:
    threads: 5
    memory: "4G"

site_calling:
    threads: 3
    memory: "4G"

variant_calling:
    threads: 3
    memory: "4G"

mtbseq:
    threads: 10
    memory: "24G"
    h_rt: "48:00:0"

tbprofiler:
    threads: 5
    memory: "6G"
    h_rt: "48:00:0"

mykrobe_pe:
    threads: 20
    memory: "16G"
    h_rt: "48:00:0"

stats_coverage:
    threads: 1
    memory: "2G"
    h_rt: "00:20:0"

run_kraken:
    threads: 20
    memory: "16G"

snp_annotation_legacy:
    threads: 1
    memory: "4G"

annotation:
    threads: 2
    memory: "4G"

compare:
    threads: 1
    memory: "4G"

site_filter:
    threads: 10
    memory: "16G"

phylogenetics:
    threads: 10
    memory: "16G"

convert_infile_fasta:
    threads: 1
    memory: "4G"

run_pyjar:
    threads: 1
    memory: "4G"
