name: kasel
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - pip
    - python=3.9.18
    - snakemake-minimal=7.32.4
    - loguru
    - graphviz
    - pytest
    - pip:
        - pandas
